@productsHost = http://localhost:4020
@usersHost = http://localhost:4021
# @productsHost = http://localhost:30020
# @usersHost = http://localhost:30021
# @productsHost = http://micro.local
# @usersHost = http://micro.local

### Health - Users
GET {{usersHost}}/health
Accept: application/json

### List Products
GET {{productsHost}}/api/products
Accept: application/json

### Get Product By Id
GET {{productsHost}}/api/products/1
Accept: application/json

### List Users
GET {{usersHost}}/api/users
Accept: application/json

### Get User By Id
GET {{usersHost}}/api/users/1
Accept: application/json

### Create User
POST {{usersHost}}/api/users
Content-Type: application/json
Accept: application/json

{
  "name": "Maria Lopez",
  "email": "maria.lopez@duocuc.cl",
  "role": "student"
}
