---
# ── PostgreSQL para cart-service ─────────────────────────────────────────────
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cart-postgres-pvc
  namespace: microservicios
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-postgres
  namespace: microservicios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-postgres
  template:
    metadata:
      labels:
        app: cart-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cart-secrets
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cart-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: cart-secrets
                  key: DB_NAME
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: cart-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cart-postgres
  namespace: microservicios
spec:
  selector:
    app: cart-postgres
  ports:
    - port: 5432
      targetPort: 5432
